development:
  adapter: mysql2
  database: badgeville_development
  pool: 5
  timeout: 5000
  socket: /tmp/mysql.sock
test: &test
  adapter: mysql2
  database: badgeville_test
  pool: 5
  timeout: 5000
  socket: /tmp/mysql.sock
production: &test
  adapter: mysql2
  database: badgeville_test
  pool: 5
  timeout: 5000
  socket: /tmp/mysql.sock
cucumber:
  <<: *test
