log4r_config:
  pre_config:
    custom_levels:
    - DEBUG
    - PARAMS
    - INFO
    - WARN
    - ERROR
    - EXCEPTION
    - FATAL
  # define all loggers ...
  loggers:
    - name      : production
      level     : WARN
      trace     : 'false'
      outputters :
    - name      : development
      level     : DEBUG
      trace     : 'true'
      outputters : 

    - name          : rails
      level         : DEBUG
      trace         : 'true'
      outputters    : 
      - RailsStdOutputter
      - datefile

    - name          : mysql
      level         : DEBUG
      trace         : 'true'
      outputters    : 
      - ActiveRecordStdOutputter
      - datefile
    - name          : mongo
      level         : DEBUG
      trace         : 'true'
      outputters    : 
      - MongoStdOutputter
      - datefile


  # define all outputters (incl. formatters)
  outputters:
  - type: DateFileOutputter
    name: datefile
    dirname: "log"
    filename: "my_app.log" # notice the file extension is needed! 
    formatter:
      date_pattern: '%H:%M:%S.%L'
      pattern     : '[%p][RAILS][%d][%l]: %m '
      type        : PatternFormatter

  - type: StdoutOutputter
    name: RailsStdOutputter
    formatter:
      date_pattern: '%H:%M:%S.%L'
      pattern     : '[%p][RAILS][%d][%l]: %m '
      type        : PatternFormatter

  - type: StdoutOutputter
    name: ActiveRecordStdOutputter
    formatter:
      date_pattern: '%H:%M:%S.%L'
      pattern     : '[%p][ACTIVERECORD][%d][%l]: %m '
      type        : PatternFormatter

  - type: StdoutOutputter
    name: MongoStdOutputter
    formatter:
      date_pattern: '%H:%M:%S.%L'
      pattern     : '[%p][MONGO][%d][%l]: %m '
      type        : PatternFormatter
