log4r_config:
  pre_config:
    custom_levels:
    - DEBUG
    - PARAMS
    - INFO
    - WARN
    - ERROR
    - EXCEPTION
    - FATAL
  # define all loggers ...
  loggers:
    - name          : rails
      level         : DEBUG
      trace         : 'true'
      outputters    : 
      - RailsStdOutputter
      - railsfile

    - name          : mysql
      level         : DEBUG
      trace         : 'true'
      outputters    : 
      - ActiveRecordStdOutputter
      - activerecordfile

    - name          : mongo
      level         : DEBUG
      trace         : 'true'
      outputters    : 
      - MongoStdOutputter
      - mongofile


  # define all outputters (incl. formatters)
  outputters:
  - type: DateFileOutputter
    name: railsfile
    dirname: "log"
    filename: "#{ENV}.log" # notice the file extension is needed! 
    formatter:
      date_pattern: '%H:%M:%S.%L %z'
      pattern     : '[%p][RAILS][%d][%l]: %m '
      type        : PatternFormatter

  - type: DateFileOutputter
    name: activerecordfile
    dirname: "log"
    filename: "#{ENV}.log" # notice the file extension is needed! 
    formatter:
      date_pattern: '%H:%M:%S.%L %z'
      pattern     : '[%p][ACTIVERECORD][%d][%l]: %m '
      type        : PatternFormatter

  - type: DateFileOutputter
    name: mongofile
    dirname: "log"
    filename: "#{ENV}.log" # notice the file extension is needed! 
    formatter:
      date_pattern: '%H:%M:%S.%L %z'
      pattern     : '[%p][MONGO][%d][%l]: %m '
      type        : PatternFormatter

  - type: StdoutOutputter
    name: RailsStdOutputter
    formatter:
      date_pattern: '%H:%M:%S.%L %z'
      pattern     : '[%p][RAILS][%d][%l]: %m '
      type        : PatternFormatter

  - type: StdoutOutputter
    name: ActiveRecordStdOutputter
    formatter:
      date_pattern: '%H:%M:%S.%L %z'
      pattern     : '[%p][ACTIVERECORD][%d][%l]: %m '
      type        : PatternFormatter

  - type: StdoutOutputter
    name: MongoStdOutputter
    formatter:
      date_pattern: '%H:%M:%S.%L %z'
      pattern     : '[%p][MONGO][%d][%l]: %m '
      type        : PatternFormatter
